hop-protocol/hop

- packages/hop-node/src/db/TransfersDb.ts
- packages/hop-node/src/watchers/BondTransferRootWatcher.ts
- packages/hop-node/src/watchers/BondWithdrawalWatcher.ts
- packages/hop-node/src/watchers/ChallengeWatcher.ts
- packages/hop-node/src/watchers/CommitTransferWatcher.ts
- packages/hop-node/src/watchers/SettleBondedWithdrawalWatcher.ts
- packages/hop-node/src/watchers/StakeWatcher.ts
- packages/hop-node/src/watchers/classes/BaseWatcher.ts
- packages/hop-node/src/watchers/classes/IBaseWatcher.ts
- packages/hop-node/src/watchers/xDomainMessageRelayWatcher.ts
Separates out sync and poller into phases;
1. preSync
2. sync
3. postSync
and
1. prePoll
2. poll
3. postPoll
- Simplifies/dries up things (only deal with syncHandler/pollHandler)
- Removes while loops
- Removes polling logic from child classes 
- Adds isAllSiblingWatchersInitialSyncCompleted() that returns true when all sibling watchers have finished the initial sync
Checks unsettled transfers only after all settle watchers have completed initial sync
> hop-node: Seperate out sync and poller phases 

- packages/hop-node/src/watchers/BondWithdrawalWatcher.ts
- packages/hop-node/src/watchers/classes/ContractBase.ts
This PR removes some RPC calls that appear to be unnecessary.
The biggest issue is that we would loop through each item marked `TransferSent` and make 5 RPC calls per chain on initial sync, in parallel, even if withdrawals were already bonded. This happened even if the transfer was bonded but the initial sync simply wasn't up-to-date.
- Do not allow txs to be sent during initial sync in order to guarantee DB state
- We had a ton of calls being made during initial sync (5 RPC calls per any transfer ever sent in our system, in parallel + an event handler per tx)
- Removes an isBonder on chain call b/c we can assume only a bonder is running this software (1 RPC call per bond withdrawal)
- Remove `const isWithdrawalBonded = bondedAmount.gt(0) || isTransferIdSpent because` DB state is …
> hop-node: refactor bondWithdrawalWatcher RPC calls

- packages/hop-node/src/watchers/SyncWatcher.ts
- packages/hop-node/src/watchers/classes/BaseWatcher.ts
- packages/hop-node/src/watchers/classes/Bridge.ts
- packages/hop-node/src/watchers/classes/ContractBase.ts
@miguelmota This PR removes newly unused code because of recent code/sync optimizations. Code removal includes "too many blocks" error.
Three top level questions that relate to these and prior updates:
1. `ready` in the ContractBase class is set to `true` [upon initialization](https://github.com/hop-protocol/hop/blob/26c98128973985ab3caf3a572b51582e85d470fc/packages/hop-node/src/watchers/classes/ContractBase.ts#L13). If I understand that correctly, this class will be set to `ready` even before the completion of the constructor code. Does it make sense to initialize it to `false` and set it to `true` on the last line of the constructor?
2. Because constructors are synchronous, is it guaranteed the last line of the most base class (in this case, ContractBase), is truly the last thing to …
> hop-node: remove unused code

- packages/frontend/src/pages/Pools/TokenWrapper/TokenWrapper.tsx
If a user goes to the Pool section of the Hop Exchange page and opens the wrap/unwrap section (for MATIC on Polygon), it shows a WWMATIC ticker instead of WMATIC. This can confuse people.
It's a small fix in hop/packages/frontend/src/pages/Pools/TokenWrapper/TokenWrapper.tsx ([line 84](https://github.com/hop-protocol/hop/blob/3501350629bc09c831056d05e06dfcda3c9a0865/packages/frontend/src/pages/Pools/TokenWrapper/TokenWrapper.tsx#L84)):
```javascript
balanceLabel={`W${wrappedToken?.symbol}:`}
```
I only removed "W" from this line 😉
> Bugfix for a "bug" that changes the WMATIC ticker to WWMATIC

- README.md
- docs/lerna.md
- docs/yarn-workspaces.md
- lerna.json
- package.json
- packages/core/yarn.lock
- packages/frontend/README.md
- packages/frontend/yarn.lock
- packages/hop-node/README.md
- packages/hop-node/yarn.lock
- packages/sdk/README.md
- packages/sdk/yarn.lock
- packages/stats-worker/yarn.lock
continues addressing #162
previously, the repo was configured to bootstrap lerna packages via `npm`. this pr enables lerna to install via `yarn`. additionally, `npx lerna link` is no longer necessary (happens during `lerna bootstrap`)
this pr also includes updated readme docs for setting up the repo for local development.
this pr also includes references for basic lerna commands (/docs)
> Meta: update lerna scripts and readme docs

- packages/hop-node/src/cli/dbDump.ts
- packages/hop-node/src/constants/constants.ts
- packages/hop-node/src/db/BaseDb.ts
- packages/hop-node/src/db/GasPricesDb.ts
- packages/hop-node/src/db/TokenPricesDb.ts
- packages/hop-node/src/db/TransfersDb.ts
- packages/hop-node/src/db/db.ts
Adds leveldb createKeyStream filter [options]( https://www.npmjs.com/package/levelup#dbcreatereadstreamoptions) to narrow lookup. Drastically improves lookup speed by having leveldb narrow the scope instead of filtering a constantly increasing list of entries.
Filter options added to `GasPricesDb` + `TokenPricesDb` `getNearest` method and `TransfersDb` db getters.
gas prices lookup example (finding an entry closest to timestamp):
without key filter
```
items: 19947
elapsed: 2430.229ms
```
with key filter
```
items: 237
elapsed: 24.927ms
```
both examples return expected entry.
Transfers db lookup example (finding entries between two dates):
without key filter
```
items: 7
elapsed: 546.952ms
```
with key filter
```
items: 7
elapsed: 14.137ms
```
both example return the same expected set of …
> hop-node: Db: Add key stream filter to filter within range

- packages/frontend/src/components/header/Header.tsx
- packages/frontend/src/config/mainnet.ts
Do not merge until regenesis is about to occur (Nov 11 9am PT)
- Disables Optimism completely as an option
- Adds explainer banner
> frontend: Disable Optimism during regenesis

- .gitignore
- packages/frontend/src/components/buttons/Button.tsx
- packages/frontend/src/components/txConfirm/AddLiquidity.tsx
- packages/frontend/src/components/txConfirm/Approval.tsx
- packages/frontend/src/components/txConfirm/ConfirmConvert.tsx
- packages/frontend/src/components/txConfirm/ConfirmSend.tsx
- packages/frontend/src/components/txConfirm/ConfirmStake.tsx
- packages/frontend/src/components/txConfirm/TxConfirm.tsx
- packages/frontend/src/components/txConfirm/UnwrapToken.tsx
- packages/frontend/src/components/txConfirm/WrapToken.tsx
- packages/frontend/src/components/txConfirm/useSendingTransaction.ts
- packages/frontend/src/pages/Send/Send.tsx
this pr prevents accidental double clicks for the modal components in `TxConfirm`.
additionally, readability is improved for the `Send` component, and tx confirm component names which were previously named the same as others are renamed with the prefix `Confirm-`.
> UI: smarter button states

- packages/hop-node/src/cli/bondWithdrawal.ts
- packages/hop-node/src/watchers/BondWithdrawalWatcher.ts
A change we made a while ago blocked the ability to bond withdrawals with the CLI. This was because the bonder fee check needed the context of a `gasCost` DB, however the CLI should not care about that, I believe.
This PR logically reorders a few items in the `bondWithdrawalWatcher` and calls `sendBondWithdrawalTx()` directly in the CLI command.
> hop-node: do not block CLI bond-withdrawal command

- packages/sdk/src/HopBridge.ts
previously, `getBondWithdrawalEstimatedGas` would set `destinationBridge` as the the `L2Bridge` of the destination chain. however, if the destination chain was mainnet ethereum, no bridge would be set.
this is now addressed by checking if the destination bridge is L1, and using the `L1Bridge` as the `destinationBridge`
> sdk: fix gas estimation for L2 -> L1 txs

- packages/hop-node/src/config/config.ts
- packages/hop-node/src/watchers/classes/Bridge.ts
- packages/sdk/src/Base.ts
- packages/sdk/src/config/config.ts
Allows the SDK and the bonder to define fees on a per-asset, per-chain basis
> hop-node: introduce a per-asset per-chain fee structure

- packages/frontend/src/components/header/TxPill.tsx
Show ENS name instead of truncated address in transactions pill if one exists for the address.
Before
After
> Use ENS name as account identifier if it exists

- packages/hop-node/src/db/TransferRootsDb.ts
- packages/hop-node/src/db/TransfersDb.ts
@miguelmota Changes are what was discussed. I verified it works on the first write when `dbTransferRoot` will be `null`.
> hop-node: read existing DB entry before getting timestamped key

- packages/hop-node/src/db/BaseDb.ts
- packages/hop-node/src/db/TransferRootsDb.ts
- packages/hop-node/src/db/TransfersDb.ts
- packages/hop-node/src/watchers/BondTransferRootWatcher.ts
- packages/hop-node/src/watchers/BondWithdrawalWatcher.ts
- packages/hop-node/src/watchers/ChallengeWatcher.ts
- packages/hop-node/src/watchers/SettleBondedWithdrawalWatcher.ts
- packages/hop-node/src/watchers/SyncWatcher.ts
- packages/hop-node/src/watchers/xDomainMessageRelayWatcher.ts
- Makes `transferId` required in `TransfersDb`, with exception to `update` function which auto assigns it ([#344](https://github.com/hop-protocol/hop/issues/344))
- Makes `transferRootId` required in `TransferRootsDb`,  with exception to `update` function which auto assigns it ([#344](https://github.com/hop-protocol/hop/issues/344))
- Simplifies `subDbX` key update in `TransfersDb`; the `update` function is simpler now
- Simplifies `subDbX` key update in `TransferRootsDb`; the `update` function is simpler now
- Cleans up the false `expected timestamped key` logs
- Removes `migration` from `TransferRootsDb`
> hop-node: Db: Clean up and simplify 

- packages/hop-node/src/watchers/BondWithdrawalWatcher.ts
Handles non-revert errors in `getIsRecipientReceivable()`.
Handles #336
> hop-node: handle rpc errors when checking if recipient is receivable

- packages/hop-node/src/cli/hopNode.ts
- packages/hop-node/src/config/config.ts
- packages/hop-node/src/config/fileOps.ts
- packages/hop-node/src/config/goerli.ts
- packages/hop-node/src/config/kovan.ts
- packages/hop-node/src/config/mainnet.ts
- packages/hop-node/src/config/staging.ts
- packages/hop-node/src/config/validation.ts
- packages/hop-node/src/watchers/ContractStateWatcher.ts
- packages/hop-node/src/watchers/SyncWatcher.ts
- packages/hop-node/src/watchers/classes/Bridge.ts
- packages/hop-node/src/watchers/watchers.ts
- Removes reliance on bonder addresses from `core` package
- Adds option to use `bonders` from config file
> hop-node: Config: Read route bonder addresses from config file instead of core package. #329

- packages/hop-node/src/gasboost/GasBoostTransaction.ts
- packages/hop-node/src/watchers/PolygonBridgeWatcher.ts
- packages/hop-node/src/watchers/classes/L2Bridge.ts
- packages/hop-node/test/gasBoostSigner.test.ts
- Uses `type: 0` for tx type for `commitTransfers` if source chain is polygon
> hop-node: L2Bridge: Use Type 0 tx type for Polygon commitTransfers txs

- packages/hop-node/src/watchers/classes/BaseWatcher.ts
- See issue [comment](https://github.com/hop-protocol/hop/issues/330#issuecomment-1021738333)
> hop-node: BaseWatcher: Don't override dry mode status if it was started with dry mode. #330

- packages/frontend/package.json
- packages/frontend/src/contexts/Web3Context.tsx
- packages/frontend/src/hooks/useSufficientBalance.ts
- packages/hop-node/package.json
- packages/sdk/package.json
- packages/sdk/src/Token.ts
- packages/sdk/src/config/metadata.ts
- packages/sdk/src/models/Chain.ts
- packages/sdk/src/version.ts
- packages/stats-worker/package.json
previously, if a user manually switched networks prior to confirming triggering a send tx, the app would use an old `provider` instance in `checkConnectedNetworkId()`. this is now addressed by recreating the function via `useCallback` which depends on `provider`.
previously, if a user did not have enough native token to pay for tx fees, the tx buttons would not be enabled and the `useSufficientBalance` hook would not display a warning message to indicate the error. this was due to the `useSufficientBalance` hook depending on the value `estimatedGasCost`. however, because the user doesn't have enough gas, `estimatedGasCost` would be undefined because of failed tx. this is now addressed by setting a default estimated gas cost.
additionally, a new field `nativeTokenSymbol` is added to the …
> sdk/ui: fix network switching and sufficient balance hook

- packages/frontend/src/contexts/Web3Context.tsx
previously, switching between networks would incorrectly return `true` if a user cancelled the `wallet_addEthereumChain` request (made by the app). this pr adds an additional double-check which ensures that `checkConnectedNetworkId` will *only* return true if the provider network matches the network id for the transaction.
> UI: fix network switching requests
